### ISSUE TITLE
Sqlite dB error using old iOS

### ISSUE THREAD

**Issue by BillMust** [Maxmad68/ibake#4]
Please kindly help my iPhone 6 with iOS12.1.4 works well using ibake list/info, but problem occurred when using ibake extract & read. Can you help me?thanks

**Comment by BillMust** [comment]
Here is the error msg:
ibake extract 657a6b695600511fc6c182344d026aa4c4ec2309 Camera-roll -d CameraRollDomain
Traceback (most recent call last):
  File "/usr/local/bin/ibake", line 389, in <module>
    extract(path, outputDir)
  File "/usr/local/bin/ibake", line 111, in extract
    allDir = c.execute('''SELECT * FROM Files WHERE flags IS 2 AND domain IS "%s"'''%domain).fetchall() # Get directories to extract (specified domain only)
sqlite3.DatabaseError: file is not a database

and the info of backup id:
ibake info 657a6b695600511fc6c182344d026aa4c4ec2309

Backup ID: 657a6b695600511fc6c182344d026aa4c4ec2309
Last Backup Date: 2020-10-19 09:01:56
Device Name: Beckie's iPhone
Device Type: iPhone 6 Plus (iPhone7,1)
Serial Number: F9CRN197G5R2
GUID: 2C152600D3011C87EEE859EA2E733949
ICCID: Unknown
IMEI: 352046077721956
UUID: 657a6b695600511fc6c182344d026aa4c4ec2309
Target Identifier: 657a6b695600511fc6c182344d026aa4c4ec2309
iOS Version: 12.3.1 (16F203)
iTunes Version: 12.9.2.5
