### ISSUE TITLE
Cannot list due to permissions

### ISSUE THREAD

**Issue by adminy** [Maxmad68/ibake#5]
```bash
All backups:
Traceback (most recent call last):
  File "/usr/local/bin/ibake", line 402, in <module>
    listBackups(path)
  File "/usr/local/bin/ibake", line 208, in listBackups
    for backupId in os.listdir(path): 
                    ^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/adminy/Library/Application Support/MobileSync/Backup/'
```

**Comment by adminy** [comment]
https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update
